### ISSUE TITLE
Postid of the video uploaded by resumable upload

### ISSUE THREAD

**Issue by stanislav80** [restfb/restfb.github.io#142]
Hi, I am trying to publish video on facebook by using resumable upload. 

Everything is OK and the video is published nicely but the problem is that when I call a getPostId() method on the GraphResponse object I get in the finalize stage, I get a null value.

Is there a way how to get to that Id?
I also tried to call fetchObject method with the uploadSessionId as a parameter, but I always get an error, that the object with the id does not exist.

Thanks.

**Comment by stanislav80** [comment]
Sorry for the useless issue. I studied it a bit more and found out that the videoid is sent in the start phase.

**Comment by nbartels** [comment]
No problem ... I try to clarify this in the documentation so your issue leads to an improvement for all visitors ;)
