### ISSUE TITLE
Send binary data with send api

### ISSUE THREAD

**Issue by nbartels** [restfb/restfb.github.io#197]
Because it is possible to send binary data via the send api we should provide a short explanation how this is be done. The connected code change is here:
https://github.com/restfb/restfb/issues/1062

**Comment by torbenw** [comment]
Thanks a lot for the very quick solution and the new documentation! I noticed some very minor mistakes in the documentation text. Maybe I can just "report" it here.

> To sen the data we use the BinaryAttachment we already used earlier.
"send"

> A good starting point is the mime type of the file, but this out of the RestFB scope.
"MIME", "this is"

**Comment by nbartels** [comment]
Many thanks, I'll add these changes soon...
