### ISSUE TITLE
Better explanation how to use the messenger api needed

### ISSUE THREAD

**Issue by nbartels** [restfb/restfb.github.io#64]
see here: https://github.com/restfb/restfb/issues/465

**Comment by chandrasekhar4u** [comment]
@nbartels due to some other task, I haven't done changes, <br/>I am able to see `messenger-recipient.md`, and `messenger-sendapi.md` already available in forked content (restfb.github.io_includes\documentation). <br/>Shall I update the same or I can create new files for messenger? can you guide me on this.<br/>
I have created a repo for example fb messenger webhook at: https://github.com/chandrasekhar4u/FBMsgrBot

Regarding: [restfb/restfb#465](https://github.com/restfb/restfb/issues/465)

**Comment by nbartels** [comment]
Okay so let me first explain the structure of the site a bit. 

In the `_data` folder you find 2 yml files. The important one is the `menu_documentation.yml`. That's the blueprint for the documentation page you find here: http://restfb.com/documentation/

There are a lot of sections and some have subsections. The sections are the menu items on the first level and the subsections the ones on the second level. You see these second level menu items if you click on their parent item in the menu.

Every section and subsection contains a `title`, a `file` and a `href`. 
The title is the section title that is written to the content. The file contains the section content as markdown. The href is the name of the anchor. This is used to scroll to the right position as you click on a menu item.

Now to the messenger part:
You find the Messenger API documentation in the menu.yml from line 75 to 110. 

There are several `messenger-*.md` and I suggest you add your documentation where it fits in. So if you have some addtional information regarding the messenger Button template. Add it to the messenger-buttontemplate.md.
If you text does not fit to the texts already present, please add a new file according to the name schema and add it to the menu file, too. 

If you need any information just ask :smile: 

One short note. You should use space for indentation in the yml and the correct count. Otherwise the parser has some problems and items are missing. I made this error several times :smiley:

**Comment by nbartels** [comment]
I think with the example chat bots, the current explanations on our side and the great https://github.com/marsbits/restfbmessenger project everyone should be able to built a application based on the messenger platform. 

Besides from that nothing happened for more than a year here. 

So I close this issue.
